#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SMWHR.Resource", IsApplication=true)]

namespace SMWHR
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int black = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int light = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int primary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primary_dark = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int primary_darker = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int white = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int btn_login = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int input_email = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int input_password = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int link_signup = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int LoginActivity = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Email = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int EmailError = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int Password = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int PasswordError = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int SignIn = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int SignInError = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int SignUpRequest = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int SigningIn = 2131099652;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme_Dark = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int AppTheme_Dark_Dialog = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
